# Fix Illegally Enchanted items
fixIllegals: true
# Fix Items over the vanilla limit
fixOverstack: true
# disable Unbreaking tag
fixUnbreakable: true
# disable Attribute Items, AttributeModifiers
fixAttribute: true
# disable Bedrock, Barrier, Light, Structure Void, Structure Block and End portal frames.
noIllegalBlocks: true
# no Custom Potions
fixPotions: true
# Anti Creative Chest NBT Abuse
antichestnbt: true
# Creative users cannot open any chests
creativechestlock: true
# Disable Use of spawn eggs. Useful for preventing Self-op, preventing crashes, etc.
nospawneggs: true
# Webhook to send alerts to
webhook-url: "YOUR_DISCORD_WEBHOOK_URL_HERE"