name: Java CI with Maven

on:
  push:
    branches: [ master, main ] # Trigger on pushes to master or main branch
  pull_request:
    branches: [ master, main ] # Trigger on pull requests to master or main branch
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v4 # Checkout your repository code

      - name: Set up JDK 17 # Spigot plugins typically require Java 17 or newer
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # Recommended distribution for OpenJDK

      - name: Build with Maven
        run: mvn clean package # Run the Maven clean and package goals

      - name: Upload Plugin Jar
        uses: actions/upload-artifact@v4 # Upload the compiled JAR as an artifact
        with:
          name: ${{ github.event.repository.name }}.jar # Name the artifact based on your repository name
          path: target/*.jar # Path to your compiled plugin JAR (adjust if your build output differs)
